spring:
  profiles:
    active: e2e
  jackson:
    deserialization:
      ACCEPT_FLOAT_AS_INT: false
---
spring:
  config:
    activate:
      on-profile: e2e
erp:
  url: http://json-server:3000

---
spring:
  config:
    activate:
      on-profile: qa
erp:
  url: http://json-server:3000

---
spring:
  config:
    activate:
      on-profile: prod
erp:
  url: http://json-server:3000