test:
  eshop:
    ui:
      baseUrl: http://localhost:3001
    api:
      baseUrl: http://localhost:8081
  erp:
    api:
      baseUrl: http://localhost:9002/erp
  tax:
    api:
      baseUrl: http://localhost:9002/tax

